name: Provide AWS EC2 instance names and type

on:
  workflow_dispatch:  # Manual trigger

jobs:
  check-aws-cli-version:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2  # Change this to your desired region
        
    - name: List EC2 name and type
      run: aws ec2 describe-instances --query "Reservations[].Instances[].Tags[?Key=='Name'].Value" --output text

    - name: List EC2 name and type t2.medium
      run: aws ec2 describe-instances  --query "Reservations[*].Instances[*].{Name:Tags[?Key=='Name'] | [0].Value, Instance:InstanceId,InstanceT:InstanceType, Status:State.Name, IP:PrivateIpAddress,  PublicIP:PublicIpAddress}"  --filters "Name=instance-type,Values='t2.medium'" --output table

    - name: EC2 START instance (dontforgetapp-dev)
      run:  aws ec2 start-instances --instance-ids i-0739d1abf28f9c741 --output text
    - name: EC2 STOP instance (dontforgetapp-dev)
      run:  aws ec2 stop-instances --instance-ids i-0739d1abf28f9c741 --output text

