name: Provide AWS EC2 instance names and type

on:
  workflow_dispatch:  # Manual trigger

jobs:
  check-aws-cli-version:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2  # Change this to your desired region
        
    - name: List EC2 name and type
      run: aws ec2 describe-instances --query "Reservations[].Instances[].Tags[?Key=='Name'].Value" --output text

    - name: List EC2 name and type t2.medium
      run: aws ec2 describe-instances  --query "Reservations[*].Instances[*].{Name:Tags[?Key=='Name'] | [0].Value, Instance:InstanceId,InstanceT:InstanceType, Status:State.Name, IP:PrivateIpAddress,  PublicIP:PublicIpAddress}"  --filters "Name=instance-type,Values='t2.medium'" --output table

    - name: EC2 START instance (dontforgetapp-dev)
      run:  aws ec2 start-instances --instance-ids i-0739d1abf28f9c741 --output text
      
    - name: Sleep for 45 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '45s'
    - name: EC2 GET PUBLIC IP of dontforgetapp-dev
      run: |
          aws ec2 describe-instances  --query "Reservations[*].Instances[*].{PublicIP:PublicIpAddress}"  --instance-id=i-0739d1abf28f9c741 --output text
          
    - name: EC2 GET PUBLIC IP of dontforgetapp-dev 2
      run: |
          IP_ADDR=$(aws ec2 describe-instances  --query "Reservations[*].Instances[*].{PublicIP:PublicIpAddress}"  --instance-id=i-0739d1abf28f9c741 --output text)
          echo "::set-output name=IP_ADDR::$IP_ADDR"
      id: ip-addr
  #echo "MAGIC_NUMBER=$MAGIC_NUMBER" >> $GITHUB_ENV

 # XXX We recommend to export all your variables at once, at the end of your job
    - name: Export variable MAGIC_NUMBER for next jobs
      uses: UnlyEd/github-action-store-variable@v3 # See https://github.com/UnlyEd/github-action-store-variable
      with:
          # Persist (store) our MAGIC_NUMBER ENV variable into our store, for the next jobs
          variables: |
            MAGIC_NUMBER=${{ steps.ip-addr.outputs.IP_ADDR }}
          
    - name: Echo IP addr
      run: |
          echo "Hello $MAGIC_NUMBER"
       
    - name: EC2 STOP instance (dontforgetapp-dev)
      run:  aws ec2 stop-instances --instance-ids i-0739d1abf28f9c741 --output text

